"use client";

import { AuthProvider } from "@/authContet/authContext";
import { CartProvider } from "@/authContet/CartContext";
import {Toaster} from "react-hot-toast";




// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthProvider>
         <CartProvider>
           {children}
        <Toaster position="top-center" ricchColors/>
         </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
